data_collection:
  batch_size: 10
  enabled: true
  interval: 1000
interaction:
  use_template_matching: true
  voice_input_enabled: true
  voice_output_enabled: true
monitor:
  interval_ms: 1000
  variables: ''
plc:
  trigger_var: MAIN.bVoiceTrigger
